---
abstract: 'localize attribute values within a scope'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Deep: '0.111'
  Test::More: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Attribute-Localize
provides:
  Moose::Meta::Attribute::Custom::Trait::Localize:
    file: lib/MooseX/Attribute/Localize.pm
    version: v0.1.2
  MooseX::Attribute::Localize:
    file: lib/MooseX/Attribute/Localize.pm
    version: v0.1.2
  MooseX::Attribute::Localize::Sentinel:
    file: lib/MooseX/Attribute/Localize.pm
    version: v0.1.2
requires:
  Moose: '0'
  Moose::Role: '0'
resources:
  bugtracker: https://github.com/yanick/MooseX-Attribute-Localize/issues
  homepage: https://github.com/yanick/MooseX-Attribute-Localize
  repository: https://github.com/yanick/MooseX-Attribute-Localize.git
version: 0.1.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
